### ISSUE TITLE
Trader Config

### ISSUE THREAD

**Issue by JTurner1992** [PackJC/gebsfish#8]
This JSON does not work on Trader Plus.

**Comment by PackJC** [comment]
@JTurner1992 Are you referring to https://github.com/PackJC/gebsfish/blob/master/Types%26Trader%26Classes/geb_traderplus.json?

Can you please give more details, error codes and issues regarding it? 

This was supplied by a contributor, and is not updated with trader plus.

**Comment by JTurner1992** [comment]
@PackJC If you have a look on the trader plus discord - I am currently with them and its not appearing in there traders. 
https://discord.com/channels/611965955588751370/1204760104612667412

**Comment by PackJC** [comment]
The trader config file had incorrect variables. The "CategoryName" was just named "Category" for the user.
